#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build.py -- noi src/*.lua vao war3map.lua cua map.

Cach dung:
    python build.py                 # tu tim map trong thu muc nay
    python build.py --map test2.w3x # chi dinh map
    python build.py --check         # chi kiem tra, khong ghi
    python build.py --strip         # go code da chen, tra war3map.lua ve ban goc

Quy trinh moi lan test:
    sua terrain trong World Editor -> Save -> chay build.py -> Ctrl+F9

World Editor ghi de war3map.lua moi lan Save, nen build.py luon la buoc
cuoi cung truoc khi test.

Script chay lai bao nhieu lan cung ra ket qua giong nhau: no cat bo khoi
da chen lan truoc (nhan dien bang dong marker) roi chen lai tu dau.
"""

import argparse
import datetime
import os
import re
import shutil
import subprocess
import sys

ROOT     = os.path.dirname(os.path.abspath(__file__))
SRC_DIR  = os.path.join(ROOT, "src")
BAK_DIR  = os.path.join(ROOT, "build")      # nam NGOAI thu muc map
MAP_EXTS = (".w3x", ".w3m")

BEGIN = "-- ==== TUTIEN BUILD BEGIN -- generated by build.py, do not edit ===="
END   = "-- ==== TUTIEN BUILD END ===="

# Bat ca marker cu lan moi, phong khi doi cau chu marker sau nay.
BLOCK_RE = re.compile(
    r"\n*^-- ==== TUTIEN BUILD BEGIN.*?^-- ==== TUTIEN BUILD END ====[ \t]*\n?",
    re.S | re.M,
)
DANGLING_RE = re.compile(r"\n*^-- ==== TUTIEN BUILD BEGIN.*\Z", re.S | re.M)

KW_RE  = re.compile(r"\b(function|if|do|end|repeat|until)\b")
DQUOTE = chr(34)
SQUOTE = chr(39)
BSLASH = chr(92)
NEWLN  = chr(10)

# Escape mot ky tu ma Lua chap nhan. \x.. \u{..} \ddd \<xuong dong> xu ly rieng.
SIMPLE_ESC = "abfnrtvz" + BSLASH + DQUOTE + SQUOTE + NEWLN + chr(13)


def die(text):
    print("[loi] " + text)
    sys.exit(1)


def find_map(explicit):
    """Tra ve duong dan thu muc map dang folder."""
    if explicit:
        p = explicit if os.path.isabs(explicit) else os.path.join(ROOT, explicit)
        if not os.path.isdir(p):
            die("khong thay thu muc map: " + p)
        return p

    found = [
        os.path.join(ROOT, n)
        for n in sorted(os.listdir(ROOT))
        if n.lower().endswith(MAP_EXTS) and os.path.isdir(os.path.join(ROOT, n))
    ]
    if not found:
        die("khong thay map dang folder (*.w3x / *.w3m) trong " + ROOT)
    if len(found) > 1:
        names = ", ".join(os.path.basename(f) for f in found)
        die("co nhieu map: %s -- dung --map de chi dinh." % names)
    return found[0]


def collect_sources():
    """src/*.lua sap theo so dau ten file, roi theo ten."""
    if not os.path.isdir(SRC_DIR):
        die("khong thay thu muc src: " + SRC_DIR)

    files = [n for n in os.listdir(SRC_DIR) if n.lower().endswith(".lua")]
    if not files:
        die("src rong -- khong co file .lua nao de noi.")

    def key(name):
        m = re.match(r"^(\d+)", name)
        return (0, int(m.group(1)), name.lower()) if m else (1, 0, name.lower())

    ordered = sorted(files, key=key)
    unnumbered = [n for n in ordered if not re.match(r"^\d+", n)]
    if unnumbered:
        print("[canh bao] file khong co so dau ten, xep cuoi: " + ", ".join(unnumbered))
    return [os.path.join(SRC_DIR, n) for n in ordered]


def read_text(path):
    with open(path, "rb") as f:
        raw = f.read()
    if raw.startswith(b"\xef\xbb\xbf"):
        raw = raw[3:]
    return raw.decode("utf-8", errors="replace")


def strip_block(text):
    """Go khoi da chen truoc do. Idempotent."""
    out, n = BLOCK_RE.subn("\n", text)
    if n == 0:
        # BEGIN con, END mat (file bi cat doi) -> cat tu BEGIN toi het.
        out, n = DANGLING_RE.subn("\n", text)
        if n:
            print("[canh bao] khoi cu thieu marker END, da cat tu BEGIN toi cuoi file.")
    return out, n


def build_block(sources):
    """Noi cac file nguon thanh mot khoi do...end duy nhat.

    Ca chuoi file nam chung mot khoi nen local o file truoc van nhin thay
    duoc o file sau. Chieu nguoc lai thi khong -- do la ly do cac module
    goi cheo nhau qua bang API trong 02_state.lua.
    """
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    parts = [
        BEGIN,
        "-- nguon: src/  |  build luc: %s  |  %d file" % (stamp, len(sources)),
        "-- Sua code o src/*.lua roi chay lai build.py. Sua truc tiep o day se mat.",
        "do",
    ]
    for path in sources:
        name = os.path.basename(path)
        body = read_text(path).replace("\r\n", "\n").rstrip()
        parts.append("")
        parts.append("--#region %s" % name)
        parts.append(body)
        parts.append("--#endregion %s" % name)
    parts.append("")
    parts.append("end")
    parts.append(END)
    return "\n".join(parts) + "\n"


def strip_lua_noise(text):
    """Bo comment va chuoi de dem tu khoa cho dung."""
    out, i, n = [], 0, len(text)
    while i < n:
        c = text[i]
        if c == "-" and text.startswith("--", i):
            m = re.match(r"--\[(=*)\[", text[i:])
            if m:
                close = "]" + m.group(1) + "]"
                j = text.find(close, i)
                i = n if j < 0 else j + len(close)
            else:
                j = text.find("\n", i)
                i = n if j < 0 else j
            continue
        m = re.match(r"\[(=*)\[", text[i:])
        if m:
            close = "]" + m.group(1) + "]"
            j = text.find(close, i)
            i = n if j < 0 else j + len(close)
            continue
        if c == DQUOTE or c == SQUOTE:
            i += 1
            while i < n and text[i] != c:
                i += 2 if text[i] == "\\" else 1
            i += 1
            continue
        out.append(c)
        i += 1
    return "".join(out)


def block_balance_check(text):
    """Kiem tra can bang khoi.

    Khong phai parser Lua day du, nhung bat duoc loi hay gap nhat khi noi
    file: thieu hoac thua mot end.
    """
    body = strip_lua_noise(text)
    depth = 0
    for m in KW_RE.finditer(body):
        kw = m.group(1)
        if kw in ("function", "if", "do", "repeat"):
            depth += 1
        else:
            depth -= 1
            if depth < 0:
                line = body.count("\n", 0, m.start()) + 1
                return False, "thua mot end quanh dong %d cua ket qua" % line
    if depth != 0:
        return False, "thieu %d end -- con khoi chua dong khi het file" % depth
    return True, "can bang khoi ok (khong co luac de kiem sau hon)"


def check_escapes(text):
    """Bat escape khong hop le trong chuoi ngan.

    Day chinh la loi WC3 bao "invalid escape sequence": duong dan model viet
    mot backslash thi \\S, \\N, \\T... deu khong phai escape hop le cua Lua.
    Cach chac an nhat cho duong dan la dung chuoi tho [[...]] -- trong do
    backslash la ky tu thuong, nen ham nay bo qua han.
    """
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if c == "-" and text.startswith("--", i):
            m = re.match(r"--\[(=*)\[", text[i:])
            if m:
                close = "]" + m.group(1) + "]"
                j = text.find(close, i)
                i = n if j < 0 else j + len(close)
            else:
                j = text.find(NEWLN, i)
                i = n if j < 0 else j
            continue
        m = re.match(r"\[(=*)\[", text[i:])
        if m:
            close = "]" + m.group(1) + "]"
            j = text.find(close, i)
            i = n if j < 0 else j + len(close)
            continue
        if c == DQUOTE or c == SQUOTE:
            quote = c
            i += 1
            while i < n and text[i] != quote:
                if text[i] == BSLASH:
                    nxt = text[i + 1] if i + 1 < n else ""
                    if (nxt not in SIMPLE_ESC and not nxt.isdigit()
                            and nxt not in ("x", "u")):
                        line = text.count(NEWLN, 0, i) + 1
                        near = text[max(0, i - 14):i + 10].replace(NEWLN, " ")
                        return False, ("escape khong hop le %s%s o dong %d cua ket qua"
                                       " -- gan: %s" % (BSLASH, nxt, line, near))
                    i += 2
                else:
                    i += 1
            i += 1
            continue
        i += 1
    return True, ""


FOURCC_RE = re.compile(r"(?<!\()\bFourCC\s*\(")

# Native da tung lam game sap tren 1.31.1. Ly do o docs/05-quyet-dinh/.
BANNED_NATIVES = {
    "GetUnitGoldCost": "ACCESS_VIOLATION ngay ca voi unit id hop le (ADR 0007)",
    "GetUnitWoodCost": "ACCESS_VIOLATION ngay ca voi unit id hop le (ADR 0007)",
}


def check_banned(text):
    """Chan nhung native da chung minh la lam sap game."""
    out = []
    body = strip_lua_noise(text)
    for name, why in BANNED_NATIVES.items():
        for m in re.finditer(r"\b%s\s*\(" % re.escape(name), body):
            line = body.count(NEWLN, 0, m.start()) + 1
            out.append("%s o dong %d -- %s" % (name, line, why))
    return out


def check_fourcc(text):
    """Canh bao khi thay FourCC goi tran.

    FourCC cua Warcraft III tra ve HAI gia tri. Trong Lua, loi goi ham o
    vi tri CUOI cua mot table constructor no ra thanh tat ca gia tri tra
    ve -- nen { FourCC(a), FourCC(b) } cho ra bang 3 phan tu, phan tu
    cuoi la so rac. Truyen so rac cho GetUnitGoldCost lam game sap.

    Quy uoc cua du an: dung id() trong 01_config.lua, no boc ngoac don
    de cat ve dung mot gia tri. Day la canh bao chu khong chan build --
    FourCC tran trong phep gan don van an toan.
    """
    out = []
    body = strip_lua_noise(text)
    for m in FOURCC_RE.finditer(body):
        line = body.count(NEWLN, 0, m.start()) + 1
        out.append("dong %d cua ket qua" % line)
    return out


def fallback_check(text):
    """Khong co luac thi chay hai phep kiem re tien nhung bat duoc
    hai loi hay gap nhat khi noi file: escape hong va lech end."""
    ok, note = check_escapes(text)
    if not ok:
        return False, note
    ok, note = block_balance_check(text)
    if not ok:
        return False, note
    return True, "escape + can bang khoi ok (khong co luac de kiem sau hon)"


def lua_syntax_check(text):
    """Chay luac neu may co; khong co thi kiem escape va can bang khoi."""
    exe = shutil.which("luac") or shutil.which("luac54") or shutil.which("luac53")
    if not exe:
        return fallback_check(text)

    os.makedirs(BAK_DIR, exist_ok=True)
    tmp = os.path.join(BAK_DIR, "_syntax_check.lua")
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    try:
        r = subprocess.run([exe, "-p", tmp], capture_output=True, text=True)
        return (r.returncode == 0, (r.stdout + r.stderr).strip() or "luac -p pass")
    except Exception as e:
        return (True, "bo qua kiem tra cu phap: %s" % e)
    finally:
        try:
            os.remove(tmp)
        except OSError:
            pass


def main():
    ap = argparse.ArgumentParser(add_help=True)
    ap.add_argument("--map", help="thu muc map (vd: test2.w3x)")
    ap.add_argument("--check", action="store_true", help="chi kiem tra, khong ghi file")
    ap.add_argument("--strip", action="store_true", help="go code da chen, khong chen lai")
    ap.add_argument("--no-backup", action="store_true", help="khong luu ban truoc do")
    args = ap.parse_args()

    map_dir = find_map(args.map)
    target = os.path.join(map_dir, "war3map.lua")
    if not os.path.isfile(target):
        die("khong thay %s -- mo map trong World Editor va Save mot lan truoc da." % target)

    original = read_text(target)
    base, stripped = strip_block(original)

    if "function main(" not in base:
        print("[canh bao] khong thay function main() trong war3map.lua goc. "
              "File co ve khong phai ban World Editor sinh ra.")

    if args.strip:
        sources = []
        final = base.rstrip() + "\n"
        label = "da go khoi code"
    else:
        sources = collect_sources()
        final = base.rstrip() + "\n\n" + build_block(sources)
        label = "da chen %d file" % len(sources)

    ok, note = lua_syntax_check(final)
    if not ok:
        print("[loi cu phap Lua] " + note)
        die("khong ghi file. Sua src/ roi chay lai.")

    banned = check_banned(final)
    if banned:
        for hit in banned:
            print("[cam] " + hit)
        die("khong ghi file. Nhung native nay lam game sap -- bo chung di.")

    for hit in check_fourcc(final):
        print("[canh bao] FourCC goi tran o %s -- dung id() neu no nam "
              "trong mot bang" % hit)

    if args.check:
        print("[check] map     : %s" % os.path.basename(map_dir))
        print("[check] khoi cu : %s" % ("co, se thay the" if stripped else "chua co"))
        for p in sources:
            print("[check]   + %s" % os.path.basename(p))
        print("[check] cu phap : %s" % note)
        print("[check] ket qua : %s, %d dong (chua ghi)" % (label, final.count("\n")))
        return

    if not args.no_backup:
        os.makedirs(BAK_DIR, exist_ok=True)
        shutil.copyfile(target, os.path.join(BAK_DIR, "war3map.prev.lua"))

    with open(target, "w", encoding="utf-8", newline="\n") as f:
        f.write(final)

    print("[ok] map     : %s" % os.path.basename(map_dir))
    print("[ok] goc     : %d dong%s"
          % (base.count("\n"), "  (da go khoi cu)" if stripped else ""))
    for p in sources:
        print("[ok]   + %s" % os.path.basename(p))
    print("[ok] cu phap : %s" % note)
    print("[ok] ghi     : %s -- %s, tong %d dong"
          % (os.path.relpath(target, ROOT), label, final.count("\n")))
    print("[ok] Gio bam Ctrl+F9 trong World Editor de test.")


if __name__ == "__main__":
    main()
