#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build.py -- noi src/*.lua vao war3map.lua cua map.

Cach dung:
    python build.py                 # tu tim map trong thu muc nay
    python build.py --map test2.w3x # chi dinh map
    python build.py --check         # chi kiem tra, khong ghi
    python build.py --strip         # go code da chen, tra war3map.lua ve ban goc

Quy trinh moi lan test:
    sua terrain trong World Editor -> Save -> chay build.py -> Ctrl+F9

World Editor ghi de war3map.lua moi lan Save, nen build.py luon la buoc
cuoi cung truoc khi test.

Script chay lai bao nhieu lan cung ra ket qua giong nhau: no cat bo khoi
da chen lan truoc (nhan dien bang dong marker) roi chen lai tu dau.
"""

import argparse
import struct
import datetime
import os
import re
import shutil
import subprocess
import sys

ROOT     = os.path.dirname(os.path.abspath(__file__))
SRC_DIR  = os.path.join(ROOT, "src")
BAK_DIR  = os.path.join(ROOT, "build")      # nam NGOAI thu muc map
MAP_EXTS = (".w3x", ".w3m")

BEGIN = "-- ==== TUTIEN BUILD BEGIN -- generated by build.py, do not edit ===="
END   = "-- ==== TUTIEN BUILD END ===="

# Bat ca marker cu lan moi, phong khi doi cau chu marker sau nay.
BLOCK_RE = re.compile(
    r"\n*^-- ==== TUTIEN BUILD BEGIN.*?^-- ==== TUTIEN BUILD END ====[ \t]*\n?",
    re.S | re.M,
)
DANGLING_RE = re.compile(r"\n*^-- ==== TUTIEN BUILD BEGIN.*\Z", re.S | re.M)

KW_RE  = re.compile(r"\b(function|if|do|end|repeat|until)\b")
DQUOTE = chr(34)
SQUOTE = chr(39)
BSLASH = chr(92)
NEWLN  = chr(10)

# Escape mot ky tu ma Lua chap nhan. \x.. \u{..} \ddd \<xuong dong> xu ly rieng.
SIMPLE_ESC = "abfnrtvz" + BSLASH + DQUOTE + SQUOTE + NEWLN + chr(13)


def die(text):
    print("[loi] " + text)
    sys.exit(1)


def find_map(explicit):
    """Tra ve duong dan thu muc map dang folder."""
    if explicit:
        p = explicit if os.path.isabs(explicit) else os.path.join(ROOT, explicit)
        if not os.path.isdir(p):
            die("khong thay thu muc map: " + p)
        return p

    found = [
        os.path.join(ROOT, n)
        for n in sorted(os.listdir(ROOT))
        if n.lower().endswith(MAP_EXTS) and os.path.isdir(os.path.join(ROOT, n))
    ]
    if not found:
        die("khong thay map dang folder (*.w3x / *.w3m) trong " + ROOT)
    if len(found) > 1:
        names = ", ".join(os.path.basename(f) for f in found)
        die("co nhieu map: %s -- dung --map de chi dinh." % names)
    return found[0]


WC3_CANDIDATES = [
    os.path.join("D:" + os.sep, "Warcraft III", "x86_64", "Warcraft III.exe"),
    os.path.join("C:" + os.sep, "Program Files (x86)", "Warcraft III",
                 "x86_64", "Warcraft III.exe"),
    os.path.join("C:" + os.sep, "Program Files", "Warcraft III",
                 "x86_64", "Warcraft III.exe"),
]


def find_wc3(explicit):
    for p in ([explicit] if explicit else []) + WC3_CANDIDATES:
        if p and os.path.isfile(p):
            return p
    return None


def pack_map(map_dir):
    """Dong goi thu muc map thanh .w3x. Tra ve duong dan file."""
    import w3mpq
    out = os.path.join(BAK_DIR, os.path.basename(map_dir))
    os.makedirs(BAK_DIR, exist_ok=True)
    n, size = w3mpq.pack(map_dir, out)
    print("[ok] dong goi: %d file, %s byte" % (n, format(size, ",")))
    print("[ok] FILE MAP : %s" % out)

    # Chep them vao thu muc Maps de hien trong danh sach map cua game.
    maps = os.path.join(os.path.expanduser("~"), "Documents", "Warcraft III",
                        "Maps")
    if os.path.isdir(maps):
        dest = os.path.join(maps, os.path.basename(map_dir))
        try:
            shutil.copyfile(out, dest)
            print("[ok] va chep : %s" % dest)
            print("            (mo Warcraft -> Single Player -> Custom Game)")
        except Exception as e:
            print("[canh bao] khong chep duoc vao Maps: %s" % e)
    return out


def run_map(map_dir, explicit):
    """Dong goi roi chay thang, khong qua World Editor.

    Hai cai bay cua World Editor mat han o day:
      - Ctrl+F9 dong goi ban trong BO NHO no, khong phai ban tren dia
      - moi lan Save no sinh lai war3map.lua, xoa sach code vua chen

    -loadfile chi nhan FILE .w3x, khong nhan thu muc -- da thu va game
    len den menu roi dung do.
    """
    exe = find_wc3(explicit)
    if exe is None:
        print("[loi] khong thay Warcraft III.exe. Dung --wc3 <duong dan> de chi dinh.")
        return 1
    w3x = pack_map(map_dir)
    print("[run] " + exe)
    print("[run] " + w3x)
    subprocess.Popen([exe, "-launch", "-loadfile", w3x])
    return 0


def write_wct(map_dir, block):
    """Chen khoi code vao o "Custom Script" cua World Editor.

    !!! MAC DINH TAT. World Editor KHONG CHIU NOI doan script lon.

    Da thu: chen khoi 183,873 byte vao war3map.wct. Doc lai thay dung
    dinh dang, luaparser xac nhan doan do la Lua hop le. Nhung lan Save
    ke tiep, World Editor ghi ra mot war3map.wct **1.86 GB** -- trong do
    van chi co DUNG MOT khoi code. Tuc chinh World Editor phinh file ra,
    khong phai script nay ghi lap.

    Chua do duoc nguong an toan. Toi khi nao do duoc thi dung --wct.

    Y TUONG thi van dung: World Editor SINH LAI war3map.lua moi lan Save,
    nen chen vao do thi Save nao cung mat. war3map.wct la noi no luu doan
    script tu viet va CHEP vao war3map.lua moi lan sinh -- dat code o day
    thi Save khong xoa ma tai tao. Chi la World Editor khong chiu noi
    kich thuoc.

    Dinh dang (do tu file World Editor tu ghi):

        uint32  phien ban = 0x80000004
        int32   1
        cstring doan custom script      <- chen o day
        int32   so trigger co text rieng = 0

    Tra ve (da ghi chua, ghi chu).
    """
    p = os.path.join(map_dir, "war3map.wct")
    if not os.path.isfile(p):
        return False, "khong thay war3map.wct"

    raw = open(p, "rb").read()
    if len(raw) < 12:
        return False, "war3map.wct qua ngan"

    ver, one = struct.unpack_from("<Ii", raw, 0)
    end = raw.find(bytes(1), 8)
    if end < 0:
        return False, "war3map.wct: khong thay ket chuoi"
    duoi = raw[end + 1:]

    out = struct.pack("<Ii", ver, one) + block.encode("utf-8") + bytes(1) + duoi
    with open(p, "wb") as f:
        f.write(out)
    return True, "war3map.wct -- %d byte" % len(out)


WCT_MAX = 64 * 1024     # war3map.wct that thi chi vai tram byte


def wct_backup():
    """Ban sao luu war3map.wct. Duoi moi la .orig; .goc la duoi CU, van
    doc duoc de ban sao luu tu truoc lan doi ten khong thanh vo dung."""
    for suffix in (".orig", ".goc"):
        q = os.path.join(BAK_DIR, "war3map.wct" + suffix)
        if os.path.isfile(q):
            return q
    return None


def check_wct_size(map_dir):
    """Bao neu war3map.wct phinh to bat thuong.

    World Editor giu doan Custom Script trong bo nho, va mot lan thu chen
    code vao do da lam no ghi ra file 1.4 GB moi lan Save. Mot lan lot
    vao commit la GitHub chan push (gioi han 100 MB).

    Phep kiem nay re, va no bat truoc khi file kip vao git.
    """
    p = os.path.join(map_dir, "war3map.wct")
    if not os.path.isfile(p):
        return
    n = os.path.getsize(p)
    if n <= WCT_MAX:
        return

    print("")
    print("[!] war3map.wct dang %s byte -- binh thuong chi vai tram." % format(n, ","))

    # Tu khoi phuc luon. De file nay nam do la lan commit sau bi GitHub
    # chan (gioi han 100 MB), va da bi chan hai lan roi.
    bak = wct_backup()
    if bak is not None and os.path.getsize(bak) <= WCT_MAX:
        shutil.copyfile(bak, p)
        print("    Da khoi phuc tu %s (%d byte)."
              % (os.path.basename(bak), os.path.getsize(p)))
    print("    World Editor VAN dang giu doan Custom Script trong bo nho:")
    print("    dong World Editor va KHONG Save, hoac xoa sach o Custom Script")
    print("    trong Trigger Editor (bam vao ten map o dau cay).")
    print("")


def world_editor_running():
    """World Editor co dang mo khong.

    No giu ban map trong bo nho no. Sua file tren dia xong ma Ctrl+F9
    ngay thi World Editor dong goi ban CU -- vao game khong thay gi doi,
    va khong co loi nao bao. Da dinh hai lan; lan thu hai mat mot buoi
    di tim loi trong code trong khi code hoan toan dung.
    """
    try:
        out = subprocess.check_output(
            ["tasklist", "/FI", "IMAGENAME eq World Editor.exe"],
            stderr=subprocess.DEVNULL)
        return b"World Editor.exe" in out
    except Exception:
        return False   # khong doan duoc thi im lang, dung canh bao bua


def part_key(name):
    """Mot doan duong dan -> khoa sap xep. Co so dau ten thi sap theo so."""
    m = re.match(r"^(\d+)", name)
    return (0, int(m.group(1)), name.lower()) if m else (1, 0, name.lower())


def rel_name(path):
    """Ten hien thi: duong dan tuong doi trong src, dung dau / cho gon."""
    return os.path.relpath(path, SRC_DIR).replace(os.sep, "/")


def collect_sources():
    """src/**/*.lua, sap theo so dau ten THU MUC roi den so dau ten FILE.

    Thu tu noi file la thu tu nap. Chi ba rang buoc that su:
    1_config phai truoc (no tao bang CFG), 2_state ngay sau (tao S va
    API), va file khoi dong phai cuoi cung. Moi loi goi cheo file khac
    deu qua API luc CHAY, nen phan giua sap kieu gi cung duoc -- xem
    ADR 0002.
    """
    if not os.path.isdir(SRC_DIR):
        die("khong thay thu muc src: " + SRC_DIR)

    found = []
    for dirpath, dirnames, filenames in os.walk(SRC_DIR):
        dirnames.sort()
        for n in filenames:
            if n.lower().endswith(".lua"):
                found.append(os.path.join(dirpath, n))
    if not found:
        die("src rong -- khong co file .lua nao de noi.")

    ordered = sorted(found, key=lambda p: [part_key(s) for s in
                                           rel_name(p).split("/")])

    loose = [rel_name(p) for p in ordered if "/" not in rel_name(p)]
    if loose:
        print("[canh bao] file nam thang trong src, khong trong thu muc con: "
              + ", ".join(loose))
    unnumbered = [rel_name(p) for p in ordered
                  if any(not re.match(r"^\d+", s)
                         for s in rel_name(p).split("/"))]
    if unnumbered:
        print("[canh bao] thieu so dau ten, xep cuoi: " + ", ".join(unnumbered))
    return ordered


def read_text(path):
    with open(path, "rb") as f:
        raw = f.read()
    if raw.startswith(b"\xef\xbb\xbf"):
        raw = raw[3:]
    return raw.decode("utf-8", errors="replace")


def strip_block(text):
    """Go khoi da chen truoc do. Idempotent."""
    out, n = BLOCK_RE.subn("\n", text)
    if n == 0:
        # BEGIN con, END mat (file bi cat doi) -> cat tu BEGIN toi het.
        out, n = DANGLING_RE.subn("\n", text)
        if n:
            print("[canh bao] khoi cu thieu marker END, da cat tu BEGIN toi cuoi file.")
    return out, n


def build_block(sources, lang=None):
    """Noi cac file nguon thanh mot khoi do...end duy nhat.

    Ca chuoi file nam chung mot khoi nen local o file truoc van nhin thay
    duoc o file sau. Chieu nguoc lai thi khong -- do la ly do cac module
    goi cheo nhau qua bang API trong 1_core/2_state.lua.
    """
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    parts = [
        BEGIN,
        "-- nguon: src/  |  build luc: %s  |  %d file" % (stamp, len(sources)),
        "-- Sua code o src/*.lua roi chay lai build.py. Sua truc tiep o day se mat.",
        "do",
        "",
        "-- Ba ten dung chung cua ca du an. Khai bao o day chu khong trong",
        "-- file nao, de moi file duoc boc trong khoi do...end rieng.",
        "local CFG, S, API",
        "",
        "-- DAU HIEU SONG. Ghi mot file NGAY khi chunk bat dau nap, bang",
        "-- native tho, khong phu thuoc dong code nao cua du an.",
        "--",
        "-- Tach duoc hai kha nang ma tu ngoai khong phan biet noi:",
        "--   khong co file nay          -> code KHONG nam trong map",
        "--   co file nay, khong co vet  -> chunk nap duoc nhung no giua chung",
        "if PreloadGenClear ~= nil then",
        "  PreloadGenClear(); PreloadGenStart()",
        '  Preload("chunk BAT DAU nap -- build %s")' % stamp,
        '  PreloadGenEnd("DarknessBoot.txt")',
        "end",
    ]
    for path in sources:
        name = rel_name(path)
        body = read_text(path).replace("\r\n", "\n").rstrip()
        parts.append("")
        parts.append("--#region %s" % name)
        # Moi file mot khoi rieng.
        #
        # Lua chi cho 200 bien local SONG CUNG LUC trong mot ham, va ca
        # ban build la mot ham. Gop 14 file vao mot khoi la 494 local --
        # map khong bien dich duoc, game bao "too many local variables".
        # Khoi rieng cho moi file thi local cua no duoc giai phong khi
        # het khoi, nen moi file co han muc 200 cua rieng no.
        #
        # Chay duoc la nho ADR 0002: moi loi goi cheo file da di qua bang
        # API tu dau, khong file nao goi thang local cua file khac.
        parts.append("do")
        parts.append(body)
        parts.append("end")
        parts.append("--#endregion %s" % name)
    # Ghi de CFG.LANG SAU moi file nguon. Dat o day chu khong sua
    # 1_config.lua tren dia: build hai ban khac tieng thi cay lam viec
    # khong bi ban, va "git diff" khong nhay len sau moi lan build.
    if lang:
        parts.append("")
        parts.append("-- build.py --lang " + lang)
        parts.append('CFG.LANG = "' + lang + '"')

    # Dau thoi gian build, in ra dong dau khi vao map. Khong co no thi
    # khong phan biet duoc "code sai" voi "dang chay ban cu" -- da can
    # mot lan voi "-nat card".
    parts.append("")
    parts.append('CFG.BUILD = "' + stamp + '"')

    parts.append("")
    parts.append("end")
    parts.append(END)
    return "\n".join(parts) + "\n"


def strip_lua_noise(text):
    """Bo comment va chuoi de dem tu khoa cho dung."""
    out, i, n = [], 0, len(text)
    while i < n:
        c = text[i]
        if c == "-" and text.startswith("--", i):
            m = re.match(r"--\[(=*)\[", text[i:])
            if m:
                close = "]" + m.group(1) + "]"
                j = text.find(close, i)
                i = n if j < 0 else j + len(close)
            else:
                j = text.find("\n", i)
                i = n if j < 0 else j
            continue
        m = re.match(r"\[(=*)\[", text[i:])
        if m:
            close = "]" + m.group(1) + "]"
            j = text.find(close, i)
            i = n if j < 0 else j + len(close)
            continue
        if c == DQUOTE or c == SQUOTE:
            i += 1
            while i < n and text[i] != c:
                i += 2 if text[i] == "\\" else 1
            i += 1
            continue
        out.append(c)
        i += 1
    return "".join(out)


def block_balance_check(text):
    """Kiem tra can bang khoi.

    Khong phai parser Lua day du, nhung bat duoc loi hay gap nhat khi noi
    file: thieu hoac thua mot end.
    """
    body = strip_lua_noise(text)
    depth = 0
    for m in KW_RE.finditer(body):
        kw = m.group(1)
        if kw in ("function", "if", "do", "repeat"):
            depth += 1
        else:
            depth -= 1
            if depth < 0:
                line = body.count("\n", 0, m.start()) + 1
                return False, "thua mot end quanh dong %d cua ket qua" % line
    if depth != 0:
        return False, "thieu %d end -- con khoi chua dong khi het file" % depth
    return True, "can bang khoi ok (khong co luac de kiem sau hon)"


def check_escapes(text):
    """Bat escape khong hop le trong chuoi ngan.

    Day chinh la loi WC3 bao "invalid escape sequence": duong dan model viet
    mot backslash thi \\S, \\N, \\T... deu khong phai escape hop le cua Lua.
    Cach chac an nhat cho duong dan la dung chuoi tho [[...]] -- trong do
    backslash la ky tu thuong, nen ham nay bo qua han.
    """
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if c == "-" and text.startswith("--", i):
            m = re.match(r"--\[(=*)\[", text[i:])
            if m:
                close = "]" + m.group(1) + "]"
                j = text.find(close, i)
                i = n if j < 0 else j + len(close)
            else:
                j = text.find(NEWLN, i)
                i = n if j < 0 else j
            continue
        m = re.match(r"\[(=*)\[", text[i:])
        if m:
            close = "]" + m.group(1) + "]"
            j = text.find(close, i)
            i = n if j < 0 else j + len(close)
            continue
        if c == DQUOTE or c == SQUOTE:
            quote = c
            i += 1
            while i < n and text[i] != quote:
                if text[i] == BSLASH:
                    nxt = text[i + 1] if i + 1 < n else ""
                    if (nxt not in SIMPLE_ESC and not nxt.isdigit()
                            and nxt not in ("x", "u")):
                        line = text.count(NEWLN, 0, i) + 1
                        near = text[max(0, i - 14):i + 10].replace(NEWLN, " ")
                        return False, ("escape khong hop le %s%s o dong %d cua ket qua"
                                       " -- gan: %s" % (BSLASH, nxt, line, near))
                    i += 2
                else:
                    i += 1
            i += 1
            continue
        i += 1
    return True, ""


FOURCC_RE = re.compile(r"(?<!\()\bFourCC\s*\(")

# Native da tung lam game sap tren 1.31.1. Ly do o docs/05-quyet-dinh/.
BANNED_NATIVES = {
    "GetUnitGoldCost": "ACCESS_VIOLATION ngay ca voi unit id hop le (ADR 0007)",
    "GetUnitWoodCost": "ACCESS_VIOLATION ngay ca voi unit id hop le (ADR 0007)",
}


def check_banned(text):
    """Chan nhung native da chung minh la lam sap game."""
    out = []
    body = strip_lua_noise(text)
    for name, why in BANNED_NATIVES.items():
        for m in re.finditer(r"\b%s\s*\(" % re.escape(name), body):
            line = body.count(NEWLN, 0, m.start()) + 1
            out.append("%s o dong %d -- %s" % (name, line, why))
    return out


def check_fourcc(text):
    """Canh bao khi thay FourCC goi tran.

    FourCC cua Warcraft III tra ve HAI gia tri. Trong Lua, loi goi ham o
    vi tri CUOI cua mot table constructor no ra thanh tat ca gia tri tra
    ve -- nen { FourCC(a), FourCC(b) } cho ra bang 3 phan tu, phan tu
    cuoi la so rac. Truyen so rac cho GetUnitGoldCost lam game sap.

    Quy uoc cua du an: dung id() trong 1_config.lua, no boc ngoac don
    de cat ve dung mot gia tri. Day la canh bao chu khong chan build --
    FourCC tran trong phep gan don van an toan.
    """
    out = []
    body = strip_lua_noise(text)
    for m in FOURCC_RE.finditer(body):
        line = body.count(NEWLN, 0, m.start()) + 1
        out.append("dong %d cua ket qua" % line)
    return out


def brace_balance_check(text):
    """Kiem tra can bang ngoac nhon.

    Mot bang mo ra ma khong dong lai thi bo dem do/if/function/end van
    bao "can bang" -- da de lot mot lan that: mot dong
    CFG.X = { bi chen nham vao giua khoi comment, va game bao
    "'}' expected (to close '{' at line N)".
    """
    body = strip_lua_noise(text)
    depth = 0
    opened_at = []
    for i, ch in enumerate(body):
        if ch == "{":
            depth += 1
            opened_at.append(body.count(NEWLN, 0, i) + 1)
        elif ch == "}":
            depth -= 1
            if opened_at:
                opened_at.pop()
            if depth < 0:
                line = body.count(NEWLN, 0, i) + 1
                return False, "thua mot } o dong %d cua ket qua" % line
    if depth != 0:
        return False, ("thieu %d } -- bang mo o dong %s cua ket qua chua dong"
                       % (depth, opened_at[0] if opened_at else "?"))
    return True, ""


def check_cross_file_locals(sources):
    """Bat file nay goi thang local function cua file khac.

    Tu khi moi file duoc boc trong khoi do...end rieng (de tranh gioi han
    200 local cua Lua), local cua file A KHONG con nhin thay duoc tu file
    B. Truoc day cung khong nen lam, nhung no tinh co chay duoc; gio thi
    thanh nil luc chay -- va nil chi no khi ai do di trung dong do.

    Moi loi goi cheo file phai di qua bang API. Xem ADR 0002.
    """
    owner, body = {}, {}
    for path in sources:
        t = strip_lua_noise(read_text(path))
        body[path] = t
        for m in re.finditer(r"^\s*local\s+function\s+(\w+)", t, flags=re.M):
            owner.setdefault(m.group(1), set()).add(path)

    out = []
    for name, homes in owner.items():
        pat = re.compile(r"(?<![%.\w])" + re.escape(name) + r"\s*\(")
        for path in sources:
            if path in homes:
                continue
            if pat.search(body[path]):
                out.append("%s goi %s() -- dinh nghia o %s"
                           % (rel_name(path), name,
                              ", ".join(rel_name(h) for h in homes)))
    return out


SYNC_OWNER   = "1_core/3_sync.lua"
SYNC_NATIVES = [
    "BlzSendSyncData",
    "BlzGetTriggerSyncData",
    "BlzTriggerRegisterPlayerSyncEvent",
    "TriggerRegisterPlayerSyncEvent",
    "SyncStoredInteger",
    "StoreInteger",
    "GetStoredInteger",
    "HaveStoredInteger",
    "FlushStoredInteger",
]


def check_sync_owner(sources):
    """Chi 3_sync.lua duoc dung native dong bo.

    Ba file giao dien truoc day moi file tu do mot bo native, tu quyet
    dinh co dong bo hay khong, va tu lui ve che do chay thang khi thieu.
    Ket qua: ba cau tra loi khac nhau cho cung mot cau hoi, va mot cai
    ten native viet sai (thieu tien to Blz) da lam ca ba im lang lui ve
    che do mot nguoi choi ma khong ai biet.

    Gio mot file tra loi cho ca du an. File khac goi thang lai la co ba
    cau tra loi. Xem ADR 0012.
    """
    out = []
    for path in sources:
        if rel_name(path) == SYNC_OWNER:
            continue
        t = strip_lua_noise(read_text(path))
        for name in SYNC_NATIVES:
            m = re.search(r"(?<![%.\w])" + re.escape(name) + r"\s*\(", t)
            if m:
                line = t.count(NEWLN, 0, m.start()) + 1
                out.append("%s dong %d goi %s() -- phai qua API.syncSend/"
                           "API.syncOn" % (rel_name(path), line, name))
    return out


def luaparser_check(text):
    """Kiem cu phap bang luaparser neu may co cai.

    build.py chi dem ngoac va dem do/end -- bat duoc hai loi hay gap
    nhat khi noi file, nhung khong phai mot bo phan tich Lua. luaparser
    thi la that: "pip install luaparser".
    """
    try:
        from luaparser import ast as lua_ast
    except ImportError:
        return None, ""
    try:
        lua_ast.parse(text)
        return True, "luaparser: cu phap hop le"
    except Exception as e:
        return False, "luaparser: %s" % e


def fallback_check(text):
    """Khong co luac thi chay hai phep kiem re tien nhung bat duoc
    hai loi hay gap nhat khi noi file: escape hong va lech end."""
    ok, note = check_escapes(text)
    if not ok:
        return False, note
    ok, note = brace_balance_check(text)
    if not ok:
        return False, note
    ok, note = block_balance_check(text)
    if not ok:
        return False, note

    ok, note = luaparser_check(text)
    if ok is False:
        return False, note
    if ok is True:
        return True, "escape + ngoac + can bang khoi ok, " + note
    return True, "escape + ngoac + can bang khoi ok (chua co luaparser)"


def lua_syntax_check(text):
    """Chay luac neu may co; khong co thi kiem escape va can bang khoi."""
    exe = shutil.which("luac") or shutil.which("luac54") or shutil.which("luac53")
    if not exe:
        return fallback_check(text)

    os.makedirs(BAK_DIR, exist_ok=True)
    tmp = os.path.join(BAK_DIR, "_syntax_check.lua")
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    try:
        r = subprocess.run([exe, "-p", tmp], capture_output=True, text=True)
        return (r.returncode == 0, (r.stdout + r.stderr).strip() or "luac -p pass")
    except Exception as e:
        return (True, "bo qua kiem tra cu phap: %s" % e)
    finally:
        try:
            os.remove(tmp)
        except OSError:
            pass


def main():
    ap = argparse.ArgumentParser(add_help=True)
    ap.add_argument("--map", help="thu muc map (vd: test2.w3x)")
    ap.add_argument("--check", action="store_true", help="chi kiem tra, khong ghi file")
    ap.add_argument("--strip", action="store_true", help="go code da chen, khong chen lai")
    ap.add_argument("--no-backup", action="store_true", help="khong luu ban truoc do")
    ap.add_argument("--lang", choices=["en", "vi"],
                    help="tieng hien cho nguoi choi; ghi de CFG.LANG")
    ap.add_argument("--run", action="store_true",
                    help="build xong chay thang map, khong qua World Editor")
    ap.add_argument("--wc3", help="duong dan Warcraft III.exe neu tu tim khong ra")
    ap.add_argument("--pack", action="store_true",
                    help="dong goi thu muc map thanh .w3x choi duoc")
    ap.add_argument("--wct", action="store_true",
                    help="NGUY HIEM: chen vao o Custom Script. Xem write_wct.")
    args = ap.parse_args()

    map_dir = find_map(args.map)
    target = os.path.join(map_dir, "war3map.lua")
    if not os.path.isfile(target):
        die("khong thay %s -- mo map trong World Editor va Save mot lan truoc da." % target)

    original = read_text(target)
    base, stripped = strip_block(original)

    if "function main(" not in base:
        print("[canh bao] khong thay function main() trong war3map.lua goc. "
              "File co ve khong phai ban World Editor sinh ra.")

    if args.strip:
        sources = []
        final = base.rstrip() + "\n"
        label = "da go khoi code"
    else:
        sources = collect_sources()
        final = base.rstrip() + "\n\n" + build_block(sources, args.lang)
        label = "da chen %d file" % len(sources)

    ok, note = lua_syntax_check(final)
    if not ok:
        print("[loi cu phap Lua] " + note)
        die("khong ghi file. Sua src/ roi chay lai.")

    if sources:
        cross = check_cross_file_locals(sources)
        if cross:
            for hit in cross:
                print("[loi] " + hit)
            die("khong ghi file. Moi file nam trong khoi do...end rieng, nen "
                "goi cheo phai di qua API (ADR 0002).")

        sync = check_sync_owner(sources)
        if sync:
            for hit in sync:
                print("[loi] " + hit)
            die("khong ghi file. Native dong bo chi duoc dung trong %s "
                "(ADR 0012)." % SYNC_OWNER)

    banned = check_banned(final)
    if banned:
        for hit in banned:
            print("[cam] " + hit)
        die("khong ghi file. Nhung native nay lam game sap -- bo chung di.")

    for hit in check_fourcc(final):
        print("[canh bao] FourCC goi tran o %s -- dung id() neu no nam "
              "trong mot bang" % hit)

    if args.check:
        print("[check] map     : %s" % os.path.basename(map_dir))
        print("[check] khoi cu : %s" % ("co, se thay the" if stripped else "chua co"))
        for p in sources:
            print("[check]   + %s" % rel_name(p))
        print("[check] cu phap : %s" % note)
        print("[check] ket qua : %s, %d dong (chua ghi)" % (label, final.count("\n")))
        return

    if not args.no_backup:
        os.makedirs(BAK_DIR, exist_ok=True)
        shutil.copyfile(target, os.path.join(BAK_DIR, "war3map.prev.lua"))

    with open(target, "w", encoding="utf-8", newline="\n") as f:
        f.write(final)

    print("[ok] map     : %s" % os.path.basename(map_dir))
    print("[ok] goc     : %d dong%s"
          % (base.count("\n"), "  (da go khoi cu)" if stripped else ""))
    for p in sources:
        print("[ok]   + %s" % rel_name(p))
    print("[ok] cu phap : %s" % note)
    print("[ok] ghi     : %s -- %s, tong %d dong"
          % (os.path.relpath(target, ROOT), label, final.count("\n")))
    # Chen vao o Custom Script cua World Editor. MAC DINH TAT -- xem
    # write_wct de biet vi sao.
    if args.wct:
        ok, note = write_wct(map_dir, build_block(sources, args.lang))
        print("[%s] wct     : %s" % ("ok" if ok else "canh bao", note))

    check_wct_size(map_dir)

    if args.pack and not args.run:
        pack_map(map_dir)
        return 0

    if args.run:
        return run_map(map_dir, args.wc3)

    if world_editor_running():
        print("")
        print("[!] WORLD EDITOR DANG MO -- DONG MAP ROI MO LAI TRUOC KHI Ctrl+F9.")
        print("    World Editor giu ban map trong bo nho no. File tren dia vua doi,")
        print("    nhung Ctrl+F9 se dong goi ban CU trong bo nho -- vao game khong")
        print("    thay gi doi, va KHONG co loi nao bao.")
        print("")
    else:
        print("[ok] Gio bam Ctrl+F9 trong World Editor de test.")


if __name__ == "__main__":
    main()
